//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Yoav.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LinksSoap", Namespace="http://tempuri.org/")]
    public partial class Links : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetYoutubeIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlaylistNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlaylistNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPlaylistOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePlaylistOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddLikeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLikesOperationCompleted;
        
        private System.Threading.SendOrPostCallback MostLikesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDBOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_NameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Links() {
            this.Url = global::Yoav.Properties.Settings.Default.Yoav_localhost_Links;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetYoutubeIdCompletedEventHandler GetYoutubeIdCompleted;
        
        /// <remarks/>
        public event GetPlaylistNumberCompletedEventHandler GetPlaylistNumberCompleted;
        
        /// <remarks/>
        public event GetPlaylistNameCompletedEventHandler GetPlaylistNameCompleted;
        
        /// <remarks/>
        public event AddPlaylistCompletedEventHandler AddPlaylistCompleted;
        
        /// <remarks/>
        public event DeletePlaylistCompletedEventHandler DeletePlaylistCompleted;
        
        /// <remarks/>
        public event AddLikeCompletedEventHandler AddLikeCompleted;
        
        /// <remarks/>
        public event GetLikesCompletedEventHandler GetLikesCompleted;
        
        /// <remarks/>
        public event MostLikesCompletedEventHandler MostLikesCompleted;
        
        /// <remarks/>
        public event GetDBCompletedEventHandler GetDBCompleted;
        
        /// <remarks/>
        public event Update_NameCompletedEventHandler Update_NameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetYoutubeId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetYoutubeId(string link) {
            object[] results = this.Invoke("GetYoutubeId", new object[] {
                        link});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetYoutubeIdAsync(string link) {
            this.GetYoutubeIdAsync(link, null);
        }
        
        /// <remarks/>
        public void GetYoutubeIdAsync(string link, object userState) {
            if ((this.GetYoutubeIdOperationCompleted == null)) {
                this.GetYoutubeIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetYoutubeIdOperationCompleted);
            }
            this.InvokeAsync("GetYoutubeId", new object[] {
                        link}, this.GetYoutubeIdOperationCompleted, userState);
        }
        
        private void OnGetYoutubeIdOperationCompleted(object arg) {
            if ((this.GetYoutubeIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetYoutubeIdCompleted(this, new GetYoutubeIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPlaylistNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetPlaylistNumber(string username) {
            object[] results = this.Invoke("GetPlaylistNumber", new object[] {
                        username});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetPlaylistNumberAsync(string username) {
            this.GetPlaylistNumberAsync(username, null);
        }
        
        /// <remarks/>
        public void GetPlaylistNumberAsync(string username, object userState) {
            if ((this.GetPlaylistNumberOperationCompleted == null)) {
                this.GetPlaylistNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlaylistNumberOperationCompleted);
            }
            this.InvokeAsync("GetPlaylistNumber", new object[] {
                        username}, this.GetPlaylistNumberOperationCompleted, userState);
        }
        
        private void OnGetPlaylistNumberOperationCompleted(object arg) {
            if ((this.GetPlaylistNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlaylistNumberCompleted(this, new GetPlaylistNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPlaylistName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPlaylistName(string username, int num) {
            object[] results = this.Invoke("GetPlaylistName", new object[] {
                        username,
                        num});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPlaylistNameAsync(string username, int num) {
            this.GetPlaylistNameAsync(username, num, null);
        }
        
        /// <remarks/>
        public void GetPlaylistNameAsync(string username, int num, object userState) {
            if ((this.GetPlaylistNameOperationCompleted == null)) {
                this.GetPlaylistNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlaylistNameOperationCompleted);
            }
            this.InvokeAsync("GetPlaylistName", new object[] {
                        username,
                        num}, this.GetPlaylistNameOperationCompleted, userState);
        }
        
        private void OnGetPlaylistNameOperationCompleted(object arg) {
            if ((this.GetPlaylistNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlaylistNameCompleted(this, new GetPlaylistNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddPlaylist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddPlaylist(string username, string name) {
            this.Invoke("AddPlaylist", new object[] {
                        username,
                        name});
        }
        
        /// <remarks/>
        public void AddPlaylistAsync(string username, string name) {
            this.AddPlaylistAsync(username, name, null);
        }
        
        /// <remarks/>
        public void AddPlaylistAsync(string username, string name, object userState) {
            if ((this.AddPlaylistOperationCompleted == null)) {
                this.AddPlaylistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPlaylistOperationCompleted);
            }
            this.InvokeAsync("AddPlaylist", new object[] {
                        username,
                        name}, this.AddPlaylistOperationCompleted, userState);
        }
        
        private void OnAddPlaylistOperationCompleted(object arg) {
            if ((this.AddPlaylistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPlaylistCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeletePlaylist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletePlaylist(string username, int num) {
            this.Invoke("DeletePlaylist", new object[] {
                        username,
                        num});
        }
        
        /// <remarks/>
        public void DeletePlaylistAsync(string username, int num) {
            this.DeletePlaylistAsync(username, num, null);
        }
        
        /// <remarks/>
        public void DeletePlaylistAsync(string username, int num, object userState) {
            if ((this.DeletePlaylistOperationCompleted == null)) {
                this.DeletePlaylistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePlaylistOperationCompleted);
            }
            this.InvokeAsync("DeletePlaylist", new object[] {
                        username,
                        num}, this.DeletePlaylistOperationCompleted, userState);
        }
        
        private void OnDeletePlaylistOperationCompleted(object arg) {
            if ((this.DeletePlaylistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePlaylistCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddLike", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddLike(string username, int num) {
            this.Invoke("AddLike", new object[] {
                        username,
                        num});
        }
        
        /// <remarks/>
        public void AddLikeAsync(string username, int num) {
            this.AddLikeAsync(username, num, null);
        }
        
        /// <remarks/>
        public void AddLikeAsync(string username, int num, object userState) {
            if ((this.AddLikeOperationCompleted == null)) {
                this.AddLikeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddLikeOperationCompleted);
            }
            this.InvokeAsync("AddLike", new object[] {
                        username,
                        num}, this.AddLikeOperationCompleted, userState);
        }
        
        private void OnAddLikeOperationCompleted(object arg) {
            if ((this.AddLikeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddLikeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLikes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetLikes(string username, int num) {
            object[] results = this.Invoke("GetLikes", new object[] {
                        username,
                        num});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetLikesAsync(string username, int num) {
            this.GetLikesAsync(username, num, null);
        }
        
        /// <remarks/>
        public void GetLikesAsync(string username, int num, object userState) {
            if ((this.GetLikesOperationCompleted == null)) {
                this.GetLikesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLikesOperationCompleted);
            }
            this.InvokeAsync("GetLikes", new object[] {
                        username,
                        num}, this.GetLikesOperationCompleted, userState);
        }
        
        private void OnGetLikesOperationCompleted(object arg) {
            if ((this.GetLikesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLikesCompleted(this, new GetLikesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MostLikes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MostLikes() {
            object[] results = this.Invoke("MostLikes", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MostLikesAsync() {
            this.MostLikesAsync(null);
        }
        
        /// <remarks/>
        public void MostLikesAsync(object userState) {
            if ((this.MostLikesOperationCompleted == null)) {
                this.MostLikesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostLikesOperationCompleted);
            }
            this.InvokeAsync("MostLikes", new object[0], this.MostLikesOperationCompleted, userState);
        }
        
        private void OnMostLikesOperationCompleted(object arg) {
            if ((this.MostLikesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostLikesCompleted(this, new MostLikesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDB(string username) {
            object[] results = this.Invoke("GetDB", new object[] {
                        username});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDBAsync(string username) {
            this.GetDBAsync(username, null);
        }
        
        /// <remarks/>
        public void GetDBAsync(string username, object userState) {
            if ((this.GetDBOperationCompleted == null)) {
                this.GetDBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDBOperationCompleted);
            }
            this.InvokeAsync("GetDB", new object[] {
                        username}, this.GetDBOperationCompleted, userState);
        }
        
        private void OnGetDBOperationCompleted(object arg) {
            if ((this.GetDBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDBCompleted(this, new GetDBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_Name", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update_Name(string username, int num, string new_name) {
            this.Invoke("Update_Name", new object[] {
                        username,
                        num,
                        new_name});
        }
        
        /// <remarks/>
        public void Update_NameAsync(string username, int num, string new_name) {
            this.Update_NameAsync(username, num, new_name, null);
        }
        
        /// <remarks/>
        public void Update_NameAsync(string username, int num, string new_name, object userState) {
            if ((this.Update_NameOperationCompleted == null)) {
                this.Update_NameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_NameOperationCompleted);
            }
            this.InvokeAsync("Update_Name", new object[] {
                        username,
                        num,
                        new_name}, this.Update_NameOperationCompleted, userState);
        }
        
        private void OnUpdate_NameOperationCompleted(object arg) {
            if ((this.Update_NameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_NameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetYoutubeIdCompletedEventHandler(object sender, GetYoutubeIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetYoutubeIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetYoutubeIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPlaylistNumberCompletedEventHandler(object sender, GetPlaylistNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlaylistNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlaylistNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPlaylistNameCompletedEventHandler(object sender, GetPlaylistNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlaylistNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlaylistNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddPlaylistCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeletePlaylistCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddLikeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetLikesCompletedEventHandler(object sender, GetLikesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLikesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLikesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MostLikesCompletedEventHandler(object sender, MostLikesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostLikesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostLikesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDBCompletedEventHandler(object sender, GetDBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Update_NameCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591